### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by nadiavanleur** [beurtschipper/Dutch-Password-List#1]
Hi! If you have time, could you update the README with how to use this code?

**Comment by spipm** [comment]
Thank you for asking. I don't feel like updating the Readme, because I think it'll become too bloated, but I can explain typical usage here. I'll simply link to this issue from the Readme.

These are Dutch wordlists and password cracking rules. The rules are for the tool hashcat, which is a tool to crack password hashes.

The hcmask files can be used with hashcat's `-a 3` option as described [here](https://hashcat.net/wiki/doku.php?id=mask_attack) and .rule files are used as described [here](https://hashcat.net/wiki/doku.php?id=rule_based_attack). Typical use with a rules file would be something like `hashcat -m 500 -a 0 my_hashes -r spipbest.rule Dutch_Norm_All.txt`.

The 'quickrules' I made to quickly manipulate a wordlist. For example, the togglefirst.rule rule simply makes the first letter of each word uppercase ('foo' becomes 'Foo'). You could do something like `hashcat --stdout -r togglefirst.rule wordlist.txt > wordlist_upper.txt` to change all first characters in the wordlist.

The scripts directory just lists some Python scripts that I used to so some scraping or parsing. I keep them there so I can easily reproduce lists later on.

The wordlists are just wordlists with Dutch words and combinations of words from different sources. You could use them when trying to crack passwords for users you suspect have a Dutch password. Otherwise I recommend wordlists from [Weakpass](https://weakpass.com/).

Does this answer your question?
